### PR TITLE
[#254] Fix specific query for violating query example in README (main)

### PR DESCRIPTION
**Pull request by korydraughn**
See issue for the formatted version of the query.

Confirmed, using PostgreSQL, the SQL does not result in an error when run manually. Of course, testing used a different resource id and AVU.

### CODE REVIEW

**Review by alanking — COMMENTED** [review]
Should we update the specific query in `TestStorageTieringMultipleQueries` as well?

We will probably hit this naturally when testing closer to UGM, but we will need to make sure to update the training slides as well. Not sure if that's worth putting in an issue or if we'll just cross that bridge when we get there.

**Comment by korydraughn** [comment]
Yes. Can go ahead and do that in this PR.

**Comment by korydraughn** [comment]
Just need to test it now.

**Comment by korydraughn** [comment]
`TestStorageTieringMultipleQueries` passed with the change.

Got it in one too!

**Comment by trel** [comment]
always nervous about 'in one'... please introduce a typo and watch it not work... 

but yes, excellent.

**Review by alanking — APPROVED** [review]
Shameless red -> green :)

Once confirmed, I think it's good to go.

**Comment by korydraughn** [comment]
Broke the query by including an invalid column name and the test failed.
Restored the query to what's included in this PR and the test passed.

**Comment by trel** [comment]
love it.  please to #.

**Comment by korydraughn** [comment]
#'d

**Pull request merged**
