### PR TITLE
[irods/irods#6251] do not explicitly link to fmt (main)

### PR DESCRIPTION
**Pull request by SwooshyCueb**
In service of irods/irods#6251

Ignore the branch name

### CODE REVIEW

**Review by korydraughn — COMMENTED** [review]
Why doesn't this change result in the addition of `fmt::fmt`?

**Comment by SwooshyCueb** [comment]
> Why doesn't this change result in the addition of `fmt::fmt`?

Because this project doesn't actually `#include` it anywhere.

**Review by korydraughn — APPROVED** [review]
Pound it.

**Comment by SwooshyCueb** [comment]
\#'d

**Review by alanking — APPROVED** [review]

**Pull request merged**
