### PR TITLE
[irods/irods#7312] Get package revision from IrodsCPackCommon

### PR DESCRIPTION
**Pull request by SwooshyCueb**

### CODE REVIEW

**Review by korydraughn — APPROVED** [review]
Add the pound.

**Review by alanking — APPROVED** [review]

**Comment by SwooshyCueb** [comment]
\#'d

**Comment by alanking** [comment]
It just occurred to me that if we want to do patch releases for 4.3.0.x, we will need to branch from just before this commit and cherry-pick changes OR branch off at the desired point for release and revert this and any other incompatible changes. That seem okay, @korydraughn / @trel?

**Comment by alanking** [comment]
Hmm... okay, so we would need to branch off of 028a60f3d5f6613140b2569f34d47c7468bbfad6~1 in order to build against 4.3.0 and cherry-pick any relevant changes.

**Comment by SwooshyCueb** [comment]
Correct

**Comment by korydraughn** [comment]
> It just occurred to me that if we want to do patch releases for 4.3.0.x, we will need to branch from just before this commit and cherry-pick changes OR branch off at the desired point for release and revert this and any other incompatible changes. That seem okay, @korydraughn / @trel?

Hmm, once we bump the version number for this repo, we'll be able to do some version checking and introduce similar logic for backwards compatibility just like @SwooshyCueb's recent fix in the GenQuery2 repo.

With that said, let's ignore 4.3.0 compatibility and move forward as is. If we need to release something for 4.3.0, we'll deal with it then.

**Pull request merged**
