### PR TITLE
[151] update README, configuration and defaults (4-2-stable)

### PR DESCRIPTION
**Pull request by trel**

### CODE REVIEW

**Comment by trel** [comment]
we can point to the policy-based implementation(s) once they are released (and re-use a lot of the text i'm removing here).

**Comment by trel** [comment]
@ccacciari does this make it clearer?

**Comment by ccacciari** [comment]
Yes, it is clearer.
Maybe is it possible to add an example of rule to invoke it?
Looking at the slides of the past year, I found an example, but it did not work:

```
$ cat tiering-1.r 
{   
  "rule-engine-instance-name": "irods_rule_engine_plugin-unified_storage_tiering-instance",
  "rule-engine-operation": "apply_storage_tiering_policy",   
  "delay-parameters": "<PLUSET>1s</PLUSET><EF>1h DOUBLE UNTIL SUCCESS OR 6 TIMES</EF>",   
  "storage-tier-groups": [       
                           "example_group_g2",       
                           "example_group"   
                         ]
}
INPUT null
OUTPUT ruleExecOut
$ irule -r "irods_rule_engine_plugin-unified_storage_tiering-instance" -F tiering-1.r 
remote addresses: xxx.yyy.xx.xxx ERROR: rcExecMyRule error.  status = -66000 SYS_NOT_SUPPORTED
```
Thanks

**Comment by ccacciari** [comment]
Sorry my fault. I did not notice that the example is already there. It works.

**Comment by trel** [comment]
Excellent - thanks.

**Pull request merged**
